// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3u4y_ognpLBGl1TVIk-j5v1CfxEgC7x8',
    appId: '1:30942702325:web:3cc813ad2d33827c95b3bc',
    messagingSenderId: '30942702325',
    projectId: 'appai-d1aec',
    authDomain: 'appai-d1aec.firebaseapp.com',
    storageBucket: 'appai-d1aec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSNCg6QEFLyyGK6AqsrlwKVRvtcrM_f90',
    appId: '1:30942702325:android:368ab4397263a4f095b3bc',
    messagingSenderId: '30942702325',
    projectId: 'appai-d1aec',
    storageBucket: 'appai-d1aec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANwgT8atJahShJo1x3mZVx9Kcw5gON0ng',
    appId: '1:30942702325:ios:6daff9b6946b2d9695b3bc',
    messagingSenderId: '30942702325',
    projectId: 'appai-d1aec',
    storageBucket: 'appai-d1aec.appspot.com',
    iosBundleId: 'com.example.appai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANwgT8atJahShJo1x3mZVx9Kcw5gON0ng',
    appId: '1:30942702325:ios:6daff9b6946b2d9695b3bc',
    messagingSenderId: '30942702325',
    projectId: 'appai-d1aec',
    storageBucket: 'appai-d1aec.appspot.com',
    iosBundleId: 'com.example.appai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3u4y_ognpLBGl1TVIk-j5v1CfxEgC7x8',
    appId: '1:30942702325:web:2f77ee43ce2faaf195b3bc',
    messagingSenderId: '30942702325',
    projectId: 'appai-d1aec',
    authDomain: 'appai-d1aec.firebaseapp.com',
    storageBucket: 'appai-d1aec.appspot.com',
  );
}
